### ISSUE TITLE
use the 3.28 gnome runtime

### ISSUE THREAD

**Issue by legacychimera247** [flathub/com.transmissionbt.Transmission#15]
as of now transmission is one of the few programs still using the 3.24 gnome runtime...unless there is a technical reason for that, wouldn't be better to use the newest one?so we wouldn't waste space with a very old runtime :)

**Comment by TingPing** [comment]
https://github.com/flathub/com.transmissionbt.Transmission/blob/master/com.transmissionbt.Transmission.json#L4
