### ISSUE TITLE
No icon in the system tray on KDE Plasma

### ISSUE THREAD

**Issue by glaubersm** [flathub/com.transmissionbt.Transmission#18]
open transmnission.
click "Edit" menu > "preferences", click  "desktop" tab.
check the option to enable the system tray icon, click "close" button.
Still no transmission icon in the system tray.

My system:
Arch Linux
pulseeffects 4.3.4
KDE Plasma 5.14 (Wayland session)
flatpak 1.0.4

**Comment by glaubersm** [comment]
system tray shows an empty space instead.

![transmission](https://user-images.githubusercontent.com/15967631/46908568-ff968300-cefa-11e8-9b44-85be65ece88e.png)

**Comment by wjt** [comment]
Interesting. I wonder whether this is to do with the icons being renamed from `transmission` to `com.transmissionbt.Transmission`.

**Comment by glaubersm** [comment]
Maybe related...
Transmission icon is wrong in the task manager and window decoration under Wayland.

![transmission](https://user-images.githubusercontent.com/15967631/48714707-66921080-ebfa-11e8-9461-1b41081272f5.png)

**Comment by TingPing** [comment]
The `rename-icon` hack will always result in things like this. Anywhere that references the old name has to be patched.

**Comment by rscm** [comment]
In elementaryOS 5.0 (Juno) happens too
And yes I enabled the notification support in this release

Check the screenshot, between redshift and volume control
![transmission-notification-wingpanel](https://i.imgur.com/U3bqnZq.jpg)

Also the icon is missing when I use <kbd>ALT</kbd>+<kbd>TAB</kbd>, but is OK in the menu and any shortcut

**Comment by glaubersm** [comment]
This bug persists.
