### ISSUE TITLE
Using GNOME Software didn't provide the french version : I had to install within a Terminal com.transmissionbt.Transmission.Locale

### ISSUE THREAD

**Issue by antistress** [flathub/com.transmissionbt.Transmission#22]
Hi,
I'm using Debian 64 bits Sid with GNOME X11 in french (flatpak version is 1.2.4-1 and gnome-software version is 3.30.6-5)
I've installed different applications from flathub using GNOME Software : some of them were translated in french, some of them don't.
For Transmission I had to open a Terminal and to manually install com.transmissionbt.Transmission.Locale
Then Transmission was translated.

Thanks

**Comment by antistress** [comment]
I've reported the bug against gnome-software here https://gitlab.gnome.org/GNOME/gnome-software/issues/705

**Comment by wjt** [comment]
Yep, this is not within the control of this Flatpak.
