### ISSUE TITLE
Update to 3.0.0

### ISSUE THREAD

**Issue by lazka** [flathub/com.transmissionbt.Transmission#27]
https://github.com/transmission/transmission/releases/tag/3.00

:)

**Comment by wjt** [comment]
Thanks! I won't have time to work on this in the near future. I expect it would be a reasonably easy update for an interested Transmission user. Most of the patches applied here are backports from upstream which are now included upstream.

**Comment by lazka** [comment]
OK, thanks. There seems to be some progress in #28 :)
