### ISSUE TITLE
Tray icon does not work on Fedora

### ISSUE THREAD

**Issue by jacobzimmermann** [flathub/com.transmissionbt.Transmission#34]
Running the Transmission 3.00 flatpak on Fedora 33. I have the "tray icons" extension installed in Gnome Shell; all apps that use tray icons (Element, MS Teams, Steam etc.) work as expected but not Transmission; even when selected in Edit/Preferences/Desktop the tray icon does not appear and closing Tranmission's main windows kills the application.

However it does correctly work when using this same flatpak in Ubuntu 20.10.

**Comment by wjt** [comment]
Try closing all those other apps, then re-opening Transmission. Does the tray icon work?

Are you using X11 or Wayland? Can you clarify exactly which extension you are using on Fedora 33 and on Ubuntu?

**Comment by jacobzimmermann** [comment]
I tried what you suggest but it doesn't work, even when Transmission is 
the first tray-enabled app I start after login. I'm running Wayland, the 
extension is Topicons Plus 
(https://extensions.gnome.org/extension/1031/topicons/)

NB: When I say it works on Ubuntu, that's in a Wayland session as well.

Best Regards,

Jacob

**Comment by wjt** [comment]
Transmission will be using Wayland. Topicons Plus doesn't work for Wayland apps. All the other apps you list are x11.

The topicons plus README suggests using https://github.com/ubuntu/gnome-shell-extension-appindicator instead. This is what Ubuntu ships with by default.
