### ISSUE TITLE
Would it be possible to upgrade to GNOME (runtime) 41? 

### ISSUE THREAD

**Issue by codingepaduli** [flathub/com.transmissionbt.Transmission#39]

**Comment by wjt** [comment]
Patches welcome :)

**Comment by wjt** [comment]
Since the GNOME 40 runtime is still supported and there have been no new Transmission releases, I would tend not to update the runtime for its own sake. In a few months the 40 runtime will be EOL and the 42 runtime will exist so there will be stronger reasons to update (imo).
