### ISSUE TITLE
"Open Folder" doesn't work

### ISSUE THREAD

**Issue by bochecha** [flathub/com.transmissionbt.Transmission#4]
Right-click on a download, you get (among other things) a "Open Folder" item.

Click it, nothing happens.

This seems to work with the Fedora-packaged Transmission, but not with the one from Flathub.

I'm using build 848fa482356ffc0295041797cebfbdf2c5f8d3e39708ee25d1e1a858e4df9b6f.

**Comment by bochecha** [comment]
Digging through the Transmission source code, I find it runs `xdg-open` to open the folder.

This works on my system, outside the Flatpak sandbox:

```
$ xdg-open file:///home/mathieu/Downloads
```

I'm presented with the Nautilus window on the specified folder.

However, inside a sandbox:

```
$ flatpak run --command=bash com.transmissionbt.Transmission 
bash-4.3$ xdg-open file:///home/mathieu/Downloads
```

The command returns, but absolutely nothing happens.

So I guess the problem is not with Transmission then, but with the implementation of xdg-open inside the sandbox.

**Comment by TingPing** [comment]
Maybe worth reporting here: https://github.com/flatpak/flatpak-xdg-utils

**Comment by bochecha** [comment]
@TingPing yes, I was about to yesterday but somehow I forgot. Thanks for the reminder, I just did it. 🙂

**Comment by wjt** [comment]
Working as of now with xdg-desktop-portal 1.0.3

**Comment by ucalyptus** [comment]
@bochecha @wjt alsoo doesn't for Windows.
