### ISSUE TITLE
seems to ignore Flatpak Persmissions

### ISSUE THREAD

**Issue by Hunanbean** [flathub/com.transmissionbt.Transmission#42]
The only permission granted is x11.
Transmission can still access and write to essentially any folder. 
With these permission levels it should not be able to write, or even read, from any folder.

Thank you

**Comment by wjt** [comment]
Transmission's manifest sets `--filesystem=host`. See #31 for why.

**Comment by Hunanbean** [comment]
Thank you, i had seen that page. The thing that got my attention is it
still can access all even when 'fully sandboxed' meaning All permissions
removed, except x11. In my rather limited knowledge about the subject, this
appears to be a bug, somewhat different than the issues discussed in
https://github.com/flathub/com.transmissionbt.Transmission/issues/31
I did not think that just allowing x11 could allow that level of access.

Thank you

**Comment by wjt** [comment]
> I did not think that just allowing x11 could allow that level of access.

It doesn't. How are you removing other permissions?

**Comment by Hunanbean** [comment]
Using Flatseal, the only permission/folder/anything i allowed was x11.

**Comment by wjt** [comment]
What does this command output?

```
flatpak run --command=cat com.transmissionbt.Transmission /.flatpak-info
```

**Comment by Hunanbean** [comment]
[Application]
name=com.transmissionbt.Transmission
runtime=runtime/org.gnome.Platform/x86_64/41

[Instance]
instance-id=2321739772
instance-path=/home/waterspell/.var/app/com.transmissionbt.Transmission
app-path=/var/lib/flatpak/app/com.transmissionbt.Transmission/x86_64/stable/70edd911f8d94089bc24b38cbf6e87d52ba7aa210bbbc100c2a5774d421bfa3a/files
app-commit=70edd911f8d94089bc24b38cbf6e87d52ba7aa210bbbc100c2a5774d421bfa3a
app-extensions=com.transmissionbt.Transmission.Locale=d799a0c9bccc50bca26c9486a648cf3683db4f3a56426ec2d556d3d0ac56bac1
runtime-path=/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/41/f0dea6ae10e738332fc17bdb652e7ce35596d06bf5c55bdbc3ef09ff1a9d9832/files
runtime-commit=f0dea6ae10e738332fc17bdb652e7ce35596d06bf5c55bdbc3ef09ff1a9d9832
runtime-extensions=org.gnome.Platform.Locale=72d8aeb72f77da6a67ff80926ed907eaef2b429e7213e3918c575a3b97149eca;org.freedesktop.Platform.GL.default=86a1c8526bda603bdfadaaa0c3c76a1afcebf75ad1706c25fee3160765650a13;org.freedesktop.Platform.GL.nvidia-495-46=7973db7099599ed18734cb4b0a550492af4993d9387a4cf5bec14631b24ce10c;org.gtk.Gtk3theme.Matcha-dark-sea=bf8c3055537a0b468520f4ec7138784a808bd3c7a196172a36680a5b0a2d40ce;org.freedesktop.Platform.VAAPI.Intel=0404936619a46191d7bbfbcf553b1cac3a671c87aa5ccdc50c655eac613d88c0;org.freedesktop.Platform.openh264=73f998362a6fc0d57e0c7e83e928d32b0ec14d10d0d94291033976bdcecc6b6b
branch=stable
arch=x86_64
flatpak-version=1.12.3
session-bus-proxy=true
system-bus-proxy=true

[Context]
shared=network;
sockets=x11;
filesystems=!xdg-run/gvfsd;!host;

[Environment]
ALSA_CONFIG_PATH=/usr/share/alsa/alsa-flatpak.conf
GI_TYPELIB_PATH=/app/lib/girepository-1.0
GST_PLUGIN_SYSTEM_PATH=/app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0
XDG_DATA_DIRS=/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/share
ALSA_CONFIG_DIR=/usr/share/alsa
__EGL_EXTERNAL_PLATFORM_CONFIG_DIRS=/etc/egl/egl_external_platform.d:/usr/lib/x86_64-linux-gnu/GL/egl/egl_external_platform.d:/usr/share/egl/egl_external_platform.d

**Comment by Hunanbean** [comment]
I see the `filesystems=!xdg-run/gvfsd;!host;` line, and i can confirm that changing other settings, such as IPC is relflected in this command, but for some reason, !host is not being changed by flatseal (or something in flatpak). So, probably not a transmission issue. After determining if i can change to permissions with the CLI flatpak commands, pointing to a flatseal issue, i will contact the appropriate parties. 

Thank you
(I think the issue is closed but i will leave that to you)

**Comment by wjt** [comment]
As described on #31, some parts of Transmission use the file chooser portal, so it is expected that you would be able to grant it access to any file on your computer in that way.

FWIW, if your goal is to confine apps, allowing them X11 access is rather like locking the front door but leaving opening the very large delivery gate at the back. Access to the X11 socket allows (e.g.) [reading all keystrokes](https://mjg59.dreamwidth.org/42320.html).

**Comment by Hunanbean** [comment]
Unfortunately i was unable to execute many flatpak applications without granting x11 access. I was trying to avoid it, but it seems time to switch to qubes.

Thanks again
