### ISSUE TITLE
Transmission stopped to show a status indicator

### ISSUE THREAD

**Issue by mks-h** [flathub/com.transmissionbt.Transmission#57]
After the latest update Transmission has stopped showing the status indicator and the appropriate option isn't present in the settings. Closing Transmission's window makes it close the connection. Running on Wayland with [AppIndicator and KStatusNotifierItem Support](https://extensions.gnome.org/extension/615/appindicator-support/) extension.

**Comment by wjt** [comment]
@bbhtt `0002-gtk-Use-reversed-domain-icon-name-throughout.patch` was dropped in 2c076fa. That patch was to fix this issue.

**Comment by bbhtt** [comment]
4.0 dropped tray icon support https://github.com/transmission/transmission/discussions/5065
