### ISSUE TITLE
Attempting to Update Transmission Results in OSTree Failure

### ISSUE THREAD

**Issue by Saroufim** [flathub/com.transmissionbt.Transmission#6]
When attempting to update com.transmissionbt.Transmission as a regular, non-root, user it fails with the following error. 

```
Updating for user: com.transmissionbt.Transmission/x86_64/stable from flathub
[####################] 1 metadata, 0 content objects fetched; 569 B transferred **
OSTree:ERROR:src/libostree/ostree-repo.c:3729:ostree_repo_load_file: assertion failed: (S_ISREG (stbuf.st_mode))
Abortado (`core' generado)

```

**Comment by TingPing** [comment]
Flatpak and OSTree version?

**Comment by Saroufim** [comment]
Flatpak 0.10.2.1
OSTree 2018.1
I'm using a fully updated Fedora 27 if that's relevant.

**Comment by TingPing** [comment]
It may be worth reporting this against flatpak itself, doesn't sound package specific.

**Comment by wjt** [comment]
Agreed that this doesn't look package-specific to me. Are you installing with `flatpak install --user` or plain `flatpak install`? I suggest trying something like `ostree fsck --repo ~/.local/share/flatpak/repo --verify-back-refs` or `ostree fsck --repo /var/lib/flatpak/repo --verify-back-refs` respectively.

**Comment by Saroufim** [comment]
I'm just trying flapak install and sudo flatpak install. 

ostree fsck --repo ~/.local/share/flatpak/repo --verify-back-refs yields:
`error: Ref ‘appstream/x86_64’ in bindings for commit 32bcc751b75ce2748ac0488bd75ff957e36df09f7d5a7a644d8db3ffadd66d12 does not resolve to that commit
`

ostree fsck --repo /var/lib/flatpak/repo --verify-back-refs yields:
```
Validating refs...
Object missing: 568d35b2766292a5ffc46e5a23b2ff2607aa29bc890b7a980a0834ef09053826.commit
error: Loading commit for ref app/com.transmissionbt.Transmission/x86_64/stable: No such metadata object 568d35b2766292a5ffc46e5a23b2ff2607aa29bc890b7a980a0834ef09053826.commit

```
