### ISSUE TITLE
No icons in help menu

### ISSUE THREAD

**Issue by Coockie** [flathub/com.transmissionbt.Transmission#64]
Hi all! There are no icons in help menu in flatpak transmission 4.0.3 in GNU/Linux Mint 21.1 Cinnamon russian localisation. See screenshot
![Screenshot_Transmission_Help](https://user-images.githubusercontent.com/6870054/232747350-d1bfc6b3-19c3-43a0-89fd-2ff00abc8bbe.png)

**Comment by Coockie** [comment]
I should say that there are no icons at all in menus.

**Comment by wjt** [comment]
That's correct. The empty space at the left of the menu that's open in your screenshot is for a checkbox.

![image](https://user-images.githubusercontent.com/86760/232774687-a78310df-f016-4cad-ad06-1f12676f0165.png)

**Comment by wjt** [comment]
I think that Mint build is using GTK 3 not GTK 4 (as in the Flatpak).

**Comment by Coockie** [comment]
So this is specificly GTK4 issue and there are should be NO icons in menu unlike in qt builds on Windows?

**Comment by wjt** [comment]
I don't know – you could ask upstream what is expected.
