### ISSUE TITLE
new update two weeks ago

### ISSUE THREAD

**Issue by rezad1393** [flathub/com.transmissionbt.Transmission#66]
the update 4.0.4 was released 2 weeks ago.

do maintainers of flathub of apps  have any rss feed that they track to be notified of updates, or is it manual checking and users having to report the updates?

**Comment by wjt** [comment]
The necessary pull request was opened 2 weeks ago, fully automatically: #65.

However I am on sabbatical and so am not checking GitHub. Please test the test build from #65 once it completes and leave a comment to confirm it works – I'll merge if so.
