### ISSUE TITLE
Flathub reports wrong version

### ISSUE THREAD

**Issue by Danik1601** [flathub/com.transmissionbt.Transmission#69]
Ftahub reports that published Transmission version is 4.0.3 while it has been 4.0.4 since https://github.com/flathub/com.transmissionbt.Transmission/commit/e0cda17f3bd0442ef03672b571fec4e810a7fcde . Gnome Software shows the same thing, so I suppose there are some problems with metadata.

![image](https://github.com/flathub/com.transmissionbt.Transmission/assets/17238959/4a778777-344b-4e3b-9f5c-95fc25291e65)
![image](https://github.com/flathub/com.transmissionbt.Transmission/assets/17238959/e2e43c89-c83c-4567-b9d7-93b91aa4149b)

**Comment by wjt** [comment]
Thanks, indeed I forgot to update https://github.com/flathub/com.transmissionbt.Transmission/blob/master/Add-release-history-to-metainfo-file.patch. Might you be able to submit a patch?

**Comment by wjt** [comment]
Fixed in a56c6e5c961670577b0c1356a3139b95223ce82c.
