### ISSUE TITLE
Installing Transmission Fails

### ISSUE THREAD

**Issue by Saroufim** [flathub/com.transmissionbt.Transmission#7]
Attempting to install transmission from flathub fails with the following error:

error: No such metadata object 568d35b2766292a5ffc46e5a23b2ff2607aa29bc890b7a980a0834ef09053826.commit

**Comment by wjt** [comment]
Is this a different computer to #6?

**Comment by Saroufim** [comment]
No, it's the same computer running the same OS.

**Comment by wjt** [comment]
I'm going to close this, let's discuss on one ticket.
