### ISSUE TITLE
Doesn't respect dark/light GNOME theme.

### ISSUE THREAD

**Issue by pchmykh** [flathub/com.transmissionbt.Transmission#79]
Flathub Transmission doesn't respect dark/light GNOME theme. 4.0.5 (a6fe2a64aa) version.

**Comment by wjt** [comment]
Does a non-Flathub Transmission follow dark/light mode?

**Comment by wjt** [comment]
I tested Fedora's `transmission-gtk` package and as I expected it does not follow the desktop's dark/light mode either.

You could pose this feature request upstream: https://github.com/transmission/transmission
